### ISSUE TITLE
Backend MongoDb work started???

### ISSUE THREAD

**Issue by creativetechify** [MohamedBoukthir/Doctor-Appointment-Booking-MERN-Stack#1]
you have created backend folder and you have schema files there, have you connected with our db yet or not???please reply sir

**Comment by MohamedBoukthir** [comment]
N I still working on it, I just finished the UI part now and I will start
with backend Part later

Don't forget to let a star 🌟 on this repository and thank you

**Comment by creativetechify** [comment]
yes sir, i have starred and bookmarked this repository, waiting eagerly to get it to complete as soon as possible please sir

**Comment by MohamedBoukthir** [comment]
just wait for me sir , i have some stuff to do and other projects

**Comment by MohamedBoukthir** [comment]
Thank you sir
I will do my best Anyway

**Comment by creativetechify** [comment]
Sir, I also want to contribute so I forked your repository and working forward by following coding with muhib tutorial, I will regular commit the repository and you can sync it / match it with ours, same I can do , right now, I have time, I am working further so do you agree with me, Sir?????

**Comment by MohamedBoukthir** [comment]
okay i will let you finish this project but please make the code clean and easy to read for the other devs

**Comment by MohamedBoukthir** [comment]
i pull all the changes that you make then i merged it 
thank you for the clean and nice code and i will merge every changes in the future

**Comment by creativetechify** [comment]
done done sir, just waiting for next videos

**Comment by MohamedBoukthir** [comment]
okay sir 💯

**Comment by creativetechify** [comment]
your repository new commits are good, I sync all your new changes

**Comment by MohamedBoukthir** [comment]
Thank you sir
In the next time open an pull request and contribute all the new changes to my master branché and then I will merge it

**Comment by MohamedBoukthir** [comment]
Glad to hear it!
